# Generated by Django 3.2.9 on 2021-11-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exploit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('system', models.TextField(blank=True, max_length=30)),
                ('protocol', models.CharField(blank=True, max_length=30)),
                ('program', models.CharField(blank=True, max_length=50)),
                ('versions', models.CharField(blank=True, max_length=80)),
                ('cve', models.CharField(blank=True, max_length=12)),
                ('cvs', models.FloatField(blank=True)),
                ('args', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(max_length=30)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReconTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('argv1', models.CharField(max_length=255)),
                ('argv2', models.CharField(blank=True, max_length=255)),
                ('argv3', models.CharField(blank=True, max_length=255)),
                ('argv4', models.CharField(blank=True, max_length=255)),
                ('argv5', models.CharField(blank=True, max_length=255)),
                ('argv6', models.CharField(blank=True, max_length=255)),
                ('argv7', models.CharField(blank=True, max_length=255)),
                ('argv8', models.CharField(blank=True, max_length=255)),
                ('argv9', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReconToolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.IntegerField(default=1)),
                ('target_id', models.IntegerField(default=1)),
                ('command', models.CharField(max_length=200)),
                ('output', models.TextField(blank=True, max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField(default=1)),
                ('port_number', models.IntegerField(default=1)),
                ('service', models.TextField(max_length=30)),
                ('port_state', models.TextField(max_length=30)),
                ('port_protocol', models.TextField(max_length=30)),
                ('port_program', models.TextField(blank=True, max_length=30)),
                ('port_version', models.CharField(blank=True, max_length=30)),
                ('port_extra_info', models.TextField(blank=True)),
                ('port_script', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('operating_system', models.TextField(blank=True)),
                ('kernel', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('scan_mode', models.IntegerField(default=1)),
            ],
        ),
    ]
