# Generated by Django 3.2.9 on 2021-11-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='scan_mode',
            new_name='mode',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='operating_system',
            new_name='system',
        ),
    ]
