# Generated by Django 3.2.9 on 2021-11-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0002_auto_20211128_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='mac',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='target',
            name='vendor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
