# Generated by Django 3.2.10 on 2022-01-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0003_auto_20211128_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='cpe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
